--- #YAML:1.0
name:                Parse-Stata-DtaReader
version:             0.68
abstract:            ~
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
